baseurl = "https://xbkingx.github.io/"
title = "Brandon King, PhD"
copyright = "&copy; 2017-2020 Brandon King"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
# disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
# googleAnalytics = ""


[params]
  name = "Brandon King, PhD"
  role = "Neural Interface and Advanced Technology Specialist"
  organization = "  "
  avatar = "portrait.jpg"
  email = "xbkingx@gmail.com"
  address = "1335 Christina Lane, Northbrook, IL 60062"
  phone = "SUBTRACT 1 from each number: (512) 551-8548"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering? If false, you can enable it locally
  #   on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and
  #   /static/js respectively)
  custom_css = []
  custom_js  = []

  # Biography section.
  #   Section will only be displayed if `content/home/about.md` exists.
  [params.about]
    interests = [
      "Brain-computer interfaces, neuroprosthetics, and biomedical devices",
      "Virtual/augmented/mixed reality interaction paradigms and challenges ",
      "Statistical analysis, machine learning, and deep learning",
      "Cryptocurrencies and blockchain technology"
    ]
    str_interests = "Research Interests"
    str_education = "Education"

    [[params.about.education]]
      course = "PhD in Neuroscience"
      institution = "Brown University"
      year = 2017

    [[params.about.education]]
      course = "BSc in Computer Science"
      institution = "Emory University"
      year = 2001

	  [[params.about.education]]
	    course = "BSc in Neuroscience"
      institution = "Emory University"
      year = 2001
  [params.curr_proj]


  # Selected Publications section.
  #   Section will only be displayed if there are publications with
  #   `selected = true` in their `+++` preamble.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  #   Section will only be displayed if there are publications in
  #   `content/publication/`.
  # [params.publications]
  #  count = 15
  #  detailed_list = true
  #  title = "Publications"
  #  subtitle = "Peer reviewed publications, conference presentations, posters, and invited speaker events"
  #  str_all = "More..."

  # Work Experience section.
  #   Section will only be displayed if there are posts in `content/workexp/`.
  [params.workexp]
    count = 20
    title = "Core Projects and Experience"
    subtitle = ""
    str_all = "Show all"
    str_read_more = "Read more"

  # Ancillary Experience section.
  #   Section will only be displayed if there are posts in `content/ancexp/`.
  [params.ancexp]
    count = 20
    title = "Ancillary Experience"
    subtitle = ""
    str_all = "Show all"
    str_read_more = "Read more"

  # Education details section.
  #   Section will only be displayed if there are files in
  #   `content/eduexp/`.
  [params.eduexp]
    title = "Education"
    subtitle = ""

  # Skills section.
  #[params.skills]
  #  title = "Skills"
  #  subtitle = ""

  # Simple publications section.
  [params.simp_pubs]
   title = "Publications and Posters"
   subtitle = "Peer reviewed publications and conference posters"

  # Public Speaking Experience section
  [params.pub_speak]
   title = "Public Speaking"
   subtitle = "Presentations and invited speaker events"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:xbkingx@gmail.com"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/xbkingx"

  # [[params.social]]
  #   icon = "twitter"
  #   icon_pack = "fa"
  #   link = "//twitter.com/GeorgeCushen"

  [[params.social]]
    icon = "mendeley"
    icon_pack = "ai"
    link = "https://www.mendeley.com/profiles/brandon-king/"

  [[params.social]]
    icon = "download"
    icon_pack = "fa"
    link = "http://bit.ly/BKing_Resume"

  # [[params.social]]
  #  icon = "github"
  #  icon_pack = "fa"
  #  link = "//github.com/xbkingx"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Experience"
  url = "#core"
  weight = 2

[[menu.main]]
  name = "Education"
  url = "#education"
  weight = 3

[[menu.main]]
  name = "Skills"
  url = "#skills"
  weight = 4


[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 5

[[menu.main]]
  name = "Speaking"
  url = "#pub_speak"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7
